resolver: nightly-2017-09-29
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
  mintty:
    win32-2-5: false
extra-deps:
# - Cabal-2.0.0.2
- mintty-0.1.1
- bindings-uname-0.1
- hpack-0.18.1
# - path-0.6.1
# - path-io-1.3.3
# - extra-1.6
# - monad-logger-0.3.25
# - hsc2hs-0.68.2

apply-ghc-options: everything
